//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PJCAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int jobID { get; set; }
        public byte sequenceNo { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public int stepID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
